# 1. Allow TMUX to send text to macOS clipboard (via OSC 52)
# Didn't work on macOS built-in terminal app
set -g set-clipboard on

# 2. Allow your trackpad/mouse wheel to interact with TMUX
set -g mouse on

bind | split-window -h
bind '\' split-window -h
bind - split-window -v
bind p display-popup -w 80% -h 80% -E $SHELL

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf


# Style
set -g pane-border-lines heavy
set -g pane-border-indicators colour
set -g pane-border-status top
