# 1. Allow TMUX to send text to macOS clipboard (via OSC 52)
# Didn't work on macOS built-in terminal app
set -g set-clipboard on

# 2. Allow your trackpad/mouse wheel to interact with TMUX
set -g mouse on

bind | split-window -h
bind '\' split-window -h
bind - split-window -v
